#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
RESULT_DIR="$ROOT_DIR/results/sensitivity/bounded"
mkdir -p "$RESULT_DIR"

CLIENT_VALUES="${CLIENT_VALUES:-1 5 10 15 20 30 40 50}"
CONCURRENCY_VALUES="${CONCURRENCY_VALUES:-1 5 10 10 10 10 10 10}"
REPEATS="${REPEATS:-5}"

for project in OurORAMFix MVPORAMFix; do
    (cd "$ROOT_DIR/$project" && chmod +x gradlew && ./gradlew clean installDist)
done

CLIENT_VALUES="$CLIENT_VALUES" CONCURRENCY_VALUES="$CONCURRENCY_VALUES" \
REPEATS="$REPEATS" N_REQUESTS="${N_REQUESTS:-1000}" BID_EXPONENT="${BID_EXPONENT:-18}" \
ROOT_BUCKET_SIZE=1 COMPETITION_BUCKET_SIZE=1 BUCKET_SIZE=3 BLOCK_SIZE="${BLOCK_SIZE:-4096}" \
BANDWIDTH="${BANDWIDTH:-10gbit}" COARSE_ADMISSION_GROUPS=0 RETAIN_ALL_HISTORY=1 \
BUILD_IMAGE=1 RUN_LABEL=bounded JAVA_HEAP_OPTS="${JAVA_HEAP_OPTS:--Xms16g -Xmx256g}" \
RESULT_CSV="$RESULT_DIR/coco.csv" \
bash "$ROOT_DIR/OurORAMFix/run_our_admission_sweep_docker_benchmark.sh"

CLIENT_VALUES="$CLIENT_VALUES" CONCURRENCY_VALUES="$CONCURRENCY_VALUES" \
REPEATS="$REPEATS" N_REQUESTS="${N_REQUESTS:-1000}" BID_EXPONENT="${BID_EXPONENT:-18}" \
BUCKET_SIZE=3 BLOCK_SIZE="${BLOCK_SIZE:-4096}" ZIPF_PARAMETER=0.0 \
BANDWIDTH="${BANDWIDTH:-10gbit}" BUILD_IMAGE=1 RUN_LABEL=bounded \
JAVA_HEAP_OPTS="${JAVA_HEAP_OPTS:--Xms16g -Xmx256g}" \
RESULT_CSV="$RESULT_DIR/mvp.csv" \
bash "$ROOT_DIR/MVPORAMFix/run_mvp_admission_sweep_docker_benchmark.sh"

python3 "$SCRIPT_DIR/plot_bounded.py"
